### ISSUE TITLE
Does it work on java11?

### ISSUE THREAD

**Issue by MeowRay** [CGJennings/jar-loader#1]
`Exception in thread "main" java.lang.AssertionError: internal error
	at net.wdsj.servercore.bootstrap.jvm.JarLoader.addToClassPath(JarLoader.java:62)
	at net.wdsj.servercore.bootstrap.clazz.ClasspathHacker.addFile(ClasspathHacker.java:43)
	at net.wdsj.servercore.bootstrap.clazz.DynamicJarClassLoader.addFile(DynamicJarClassLoader.java:53)
	at net.wdsj.servercore.bootstrap.clazz.DynamicJarClassLoader.addFile(DynamicJarClassLoader.java:73)
	at net.wdsj.servercore.bootstrap.WdsjBootStrap.init(WdsjBootStrap.java:100)
	at net.wdsj.servercore.bootstrap.WdsjBootStrap.main(WdsjBootStrap.java:52)
	at net.wdsj.mcserver.wdsjserveriniter.Main.main(Main.java:54)
Caused by: java.lang.UnsupportedOperationException: did you forget -javaagent:<jarpath>?
	at net.wdsj.servercore.bootstrap.jvm.JarLoader.getAddUrlMethod(JarLoader.java:169)
	at net.wdsj.servercore.bootstrap.jvm.JarLoader.addToClassPath(JarLoader.java:53)
	... 6 more
`

**Comment by MeowRay** [comment]
Oh sorry, it works well, stupid i used maven relocation
![image](https://user-images.githubusercontent.com/29674595/113147574-79ee2580-9263-11eb-82f0-d5cb9593b5c7.png)
